language: ruby
addons:
  sauce_connect: true
  postgresql: "9.4"
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database pa_website_test_db;' -U postgres

