language: ruby
addons:
  sauce_connect: true
  postgresql: "9.4"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake teaspoon
  - rake spec
before_script:
  - psql -c 'create database pa_website_test_db;' -U postgres

